### ISSUE TITLE
Sign releases

### ISSUE THREAD

**Issue by grote** [stevesoltys/backup#20]
Publishing unsigned releases is not only bad for security, it also doesn't work with the latest AOSP:

```
I PackageManager: /system/priv-app/Backup changed; collecting certs
W PackageManager: Failed to scan /system/priv-app/Backup: Package /system/priv-app/Backup/Backup.apk has no certificates at entry AndroidManifest.xml
```

After signing the unsigned APK, the app gets picked up as expected.

**Comment by stevesoltys** [comment]
Yeah, that makes sense. Thanks for opening an issue.

Most people (including myself) using this are building / signing the app with AOSP, so the issue likely hasn't come up for that reason.

This also means I have no way to test, so I'm not sure when I will be able to get around to it.

**Comment by stevesoltys** [comment]
@grote since we are using prebuilts now and the platform key signature is required, do you think this is still applicable?

**Comment by thestinger** [comment]
Since the platform key is required, it will generally signed as part of building of the OS. It's still *possible* to sign it with the platform key separately and ship an out-of-band update. In this case, I don't think it's particularly useful. I want to do that with Vanadium (Chromium) because Chromium has regular release cycles with security updates not lining up with the Android cycles. For this app, it's not like there are going to be regular security updates though.

**Comment by stevesoltys** [comment]
Closing for the above reason.

**Comment by SebiderSushi** [comment]
Hello i just came across the discussion about signing seedvault with the platform key and i have one question:

How does google provide their backup transport without platfrom keys?

Would be happy about a quick answer or a hint to the right recources if the topic if more convoluted, thanks!

**Comment by grote** [comment]
There was some discussion somewhere (don't remember where, @stevesoltys?) about the possibility of making the platform key signature optional.

**Comment by stevesoltys** [comment]
@grote https://github.com/stevesoltys/seedvault/issues/58

I believe this was it.

**Comment by grote** [comment]
Thanks Steve! That's was indeed it.

@SebiderSushi would you maybe like to document the information there in the wiki or README for others?
