### ISSUE TITLE
AOSP documentation on the backup APIs

### ISSUE THREAD

**Issue by SebiderSushi** [stevesoltys/backup#21]
Forgive me if this is not the right place to ask or if i might have searched the web more thorough.
My question is: Which documentation has been used in order to implement this application and if the process of doing so might be documented in the wiki.
Because: I have tried a lot to find any documentation of the APIs for an Android backup service but i could not find any useful resources. It almost seems to me as if Google is actively not promoting this information to hinder diversity in this area and in order to hold offering a backup service more or less a monopole to themselves. The restrictiveness on the necessary system permission also supports this suspicion.
Also i would want to know what exactly can be done using the given APIs.
Please correct me if i jumped to any wrong conclusions and if there _is_ a conclusive and complete documentation on those APIs (in addition to finding the relevant methods in the AOSP source code) i would be very glad about a hint.

**Comment by stevesoltys** [comment]
Since this application is compiled with AOSP, you would need to dive into the source code for the operating system. There isn't much documentation on this because that code is not meant to be used by app developers. The backup permission is likely a system permission for security reasons, or just because Google doesn't provide any other actual implementation of `BackupTransport` except the proprietary one.

If you're looking for what AOSP code I referenced to develop this application, you can find that here:

https://github.com/aosp-mirror/platform_frameworks_base/tree/master/core/java/com/android/internal/backup
