### ISSUE TITLE
Allow user to create NON-encrypted backups

### ISSUE THREAD

**Issue by ASerbinski** [stevesoltys/backup#349]
Encrypted backups are a great thing! However, when the backup location is fully trusted, the encryption becomes a hindrance rather than a benefit, because it adds complexity to the process of modifying the backed up data, and because it creates a risk of data loss if the user loses or doesn't have access to their secret codes.

Obviously I support the use of a big ugly warning when enabling this feature -- "the backups will not be encrypted and therefore if a 3rd party is able to access them, they will have access to all of your data, probably giving them the ability to commit identity theft. Do not enable this option unless your backup location is fully secure!!! Are you sure you wish to proceed?"

**Comment by upintheairsheep** [comment]
This is especially important for people with an external USB drive.

**Comment by akoyaxd** [comment]
Related to #138

**Comment by grote** [comment]
Sorry, this is not planned. Some reasons outlined here: https://github.com/seedvault-app/seedvault/issues/138#issuecomment-891808435

**Comment by hockeymikey** [comment]
@grote I do not think that is a valid reason to close. Just because it's not planned doesn't mean an issue shouldn't be kept for discussion around it or if someone (like myself) would like to come by and implement it. It's a feature that is very very enticing to me (and others) and just like my Android 8 builds of seedvault (which I have been slacking on and should PR upstream someday, but just haven't had the time) the community might want to try their hand, even if you do not wish to (which is fine, priorities is understandable).

**Comment by chirayudesai** [comment]
@hockeymikey we aren't going to be implementing this in SeedVault for the reasons explained.

You're free to do it on your own of course, but it's not something we want to support ourselves.

Nice to hear that you've got android 8 builds, however that's also not something we can support.

At the moment we only develop on android12, all the other branches don't really get updates, since we don't have the resources to support multiple versions. And android12 has had significant changes, so it wouldn't be trivial to backport either.

**Comment by hockeymikey** [comment]
@chirayudesai Nobody is telling you to support anything or to implement it. You keep bringing up that point, but it doesn't matter. Drop it. Disagree on the backporting lift, but we will see who's correct in due time I'm sure. But for anyone reading this and has an interest in the Android 8 support, check out my profile, more than happy to help too (off-topic but just wanted to touch briefly).
