### ISSUE TITLE
Make use of signature spoofing

### ISSUE THREAD

**Issue by rugk** [stevesoltys/backup#39]
In https://github.com/stevesoltys/backup/issues/8#issuecomment-515891338 you wrote:
> Unfortunately, it looks like a backup app not only needs the system-only backup permission, but also needs to access hidden APIs. Google has been cracking down on their usage and the only way I have found to still use them is to sign the backup application with the platform private key.

I am no Android developer and have no big knowledge here, but from what I read, this looks like the same problem [the microG project also faced](https://microg.org/).

They solved it by spoofing googles signature using [signature spoofing](https://github.com/microg/android_packages_apps_GmsCore/wiki/Signature-Spoofing). Can't you do/use the same (on OSes that support signature spoofing, of course, i.e. basically nearly all microG-compatible builds) to spoof the "platform private key"?

This would make installation way easier, considering you "only" need to install a ZIP then (and allow signature spoofing for this app).
Especially as there already are patch tools that can add that capability to some OSes. (with some effort, but it's still easier than building your own whole device based on the AOSP code)

**Comment by Lanchon** [comment]
> this looks like the same problem the microG project also faced.

most likely, no.

the play services client library checks that it is talking to genuine play services by asking android for the signing cert of the play services app.

sig-spoof, when applicable, only returns a fake cert to an app when it asks android for some app's cert using a specific API. android itself never invokes said API, so sig-spoof is not visible to android. this means that android's security model is not affected at all by sig-spoof: a sig-spoof app cannot be used to update a spoofed app, it cannot access private data of other apps protected by the spoofed signature, etc, because sig-spoof app actual signature seen by android differs from the signature of the spoofed app, and thus to android the sig-spoof and spoofed apps are completely unrelated.

i do not know how new androids closed access to private APIs. it might ask for certs to the exact API patched by sig-spoof, but that would be extremely unlikely. it is to be expected that it instead uses a specific, ah hoc, extremely fast API to answer the "is platform code calling me?" question.

sig-spoof is very restricted on its powers and applications. a better system would allow "signature replacement", whereby a sufficiently privileged user could ask the system to consider a certain package as if signed by an arbitrarily provided signature for all intents and purposes.

another solution would be to simply add more platform keys to a platform. IDK, but i doubt platform keys are limited to a single key. even if that is true, the "is this a platform key?" check could be patched.

finally a note...

keep in mind that lineage4microg builds DO NOT SUPPORT SIG-SPOOF, and that is the reason why i do not consider them for use. instead they have s closed, limited sig-spoof implementation that ONLY THEY CAN USE, and no one else, which is evil. i had a discussion with the team about it before dropping L4M completely from my life, to no avail.

i have no idea whether their non-standard sig-spoof source-patched builds can be binary-patched over again successfully or not. i will not update my patching tools to support L4M. (nanolx patcher is actually my patcher bundled to run in recovery.)

**Comment by rugk** [comment]
Okay, thanks FYI. So it seems this cannot solve the problem here.

**Comment by Lanchon** [comment]
yes, but bending platform key restrictions by other means is entirely possible.

**Comment by SebiderSushi** [comment]
The following is out of context for Seedvault.

@Lanchon 
> keep in mind that lineage4microg builds DO NOT SUPPORT SIG-SPOOF, and that is the reason why i do not consider them for use. instead they have s closed, limited sig-spoof implementation that ONLY THEY CAN USE, and no one else, which is evil. i had a discussion with the team about it before dropping L4M completely from my life, to no avail.

I don't see anything evil done my the lineageos4microg team?

The sources for their docker image that they use to build their releases [document that they are using the usual sigspoof patches](https://github.com/lineageos4microg/docker-lineage-cicd#signature-spoofing). If you take a look at their [build script](https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/src/build.sh#L197) you can see how they simply restrict the signature spoofing permission to [privileged system apps that are signed with the proper key](https://developer.android.com/guide/topics/manifest/permission-element). No black magic here.

As far as i can tell the whole thing is just a security consideration. Of course, if you need something else for your use case you won't choose LineageOS for MicroG, but for their target audience it is just not required that any packages other than the preinstalled microG ones may spoof their signature so they naturally avoid any additional security implications.
