### ISSUE TITLE
Transfer of some files fails

### ISSUE THREAD

**Issue by kroeckx** [stevesoltys/backup#423]
I'm using seedvault 11-2.3 on a lineageos 18.1 with nextcloud 3.20.3.

Every time the backup runs I get notifications from nextcloud that transfers of seedvault files failed. It's showing that the local file is missing.

Could it be that a temporary file is made but that it's deleted before nextcloud is able to transfer it?

**Comment by grote** [comment]
This sounds like a Nextcloud issue. Is it working fine with DavX5 or when using the phone storage (better USB drive) as backup location?

**Comment by kroeckx** [comment]
I'm not sure why you think this is a nextcloud issue.

I've not tried using using DAVx5, I don't have a need to sync things, I'm just looking for a backup solution.

I assume that if I set seedvault up to use the phone storage, and then tell nextclould to keep that folder in sync it will work. It works properly for keeping photo's in sync. I assume this works in a similar way, except that it doesn't keep the backup files on the phone to reduce storage. It just seems to delete it too soon.

**Comment by grote** [comment]
> I'm not sure why you think this is a nextcloud issue.

Because I've seen the same thing with Nextcloud, written that code and improved Nextcloud's code. Also Seedvault isn't uploading/transferring files itself. Nextcloud does.

Hence I was asking: Is it working fine with DavX5 or when using the phone storage (better USB drive) as backup location?

> I've not tried using using DAVx5, I don't have a need to sync things

Nextcloud always keeps the files locally. DavX5 doesn't.
