### ISSUE TITLE
Unable to launch restore activity on secondary user profile

### ISSUE THREAD

**Issue by oaymn** [stevesoltys/backup#428]
**Device info :**
- OS : DivestOS 19.1
- Seedvault version : 12-3.0

Since we have to trigger the restore activity manually after creating a new user, I tried the following options but none of them worked.

**1st option :**

Trying to trigger a full system restore using ``*#*#7378673#*#*``/``*#*#RESTORE#*#*`` as described in the  [FAQ](https://github.com/seedvault-app/seedvault/wiki/FAQ#how-to-restore-after-passing-through-setup-wizard) did not work on the secondary user, instead it launched the UI on the primary user.

**2nd option :**

Trying to start the restore activity from the shell using the command  ``adb shell am start-activity -a com.stevesoltys.seedvault.RESTORE_BACKUP`` failed throwing the following exception : 

```java
Starting: Intent { act=com.stevesoltys.seedvault.RESTORE_BACKUP }

Exception occurred while executing 'start-activity':
java.lang.SecurityException: Permission Denial: starting Intent { act=com.stevesoltys.seedvault.RESTORE_BACKUP flg=0x10000000 cmp=com.stevesoltys.seedvault/.restore.RestoreActivity } from null (pid=15340, uid=2000) requires com.stevesoltys.seedvault.RESTORE_BACKUP
	at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1059)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:983)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:672)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1252)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1224)
	at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:2952)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:572)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:201)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:8656)
	at android.os.Binder.shellCommand(Binder.java:950)
	at android.os.Binder.onTransact(Binder.java:834)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5167)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2519)
	at android.os.Binder.execTransactInternal(Binder.java:1184)
	at android.os.Binder.execTransact(Binder.java:1143)
```

**3nd option :**

Trying to launch the restore activity using the [Activity Launcher app](https://github.com/butzist/ActivityLauncher) also failed, the logs are provided below (not sure if it helps): 

```ruby
07-21 22:40:10.087  1334  9572 W ActivityTaskManager: Permission Denial: starting Intent { flg=0x14000000 cmp=com.stevesoltys.seedvault/.restore.RestoreActivity } from ProcessRecord{62f317c 16421:de.szalkowski.activitylauncher/u0a154} (pid=16421, uid=10154) requires com.stevesoltys.seedvault.RESTORE_BACKUP
07-21 22:40:10.088 16421 16421 W System.err: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x14000000 cmp=com.stevesoltys.seedvault/.restore.RestoreActivity } from ProcessRecord{62f317c 16421:de.szalkowski.activitylauncher/u0a154} (pid=16421, uid=10154) requires com.stevesoltys.seedvault.RESTORE_BACKUP`
```

**Additional info :**

I have already set the backup transport for the secondary user as per this [comment](https://github.com/seedvault-app/seedvault/issues/77#issuecomment-696752898).

**Comment by grote** [comment]
Your ROM is not allowing you to start that activity. Looks like a ROM integration issue to me. Not sure how dialer codes are supposed to work across users.

**Comment by oaymn** [comment]
I see.
Thanks!

**Comment by steadfasterX** [comment]
for me it looks like [this](https://github.com/seedvault-app/seedvault/commit/b2cd3c76a3445066846f42fddfa366934b5ef050) is the reason why `am` cannot start the activity anymore.. which makes it impossible (without _root_) to open the restore dialog by adb on a secondary user or work profile (e.g. created by insular or shelter).

That means this looks to me (other then @grote mentioned) it's not an OS integration issue but instead a wanted restricted behavior by SeedVault itself - and/or an issue in its AndroidManifest. 

possible workarounds I am aware of are (only _root_ has been tested though):
- _if you build ur own OS:_ build SeedVault without that [mentioned commit](https://github.com/seedvault-app/seedvault/commit/b2cd3c76a3445066846f42fddfa366934b5ef050) (u likely do **not** want that)
- _if you build ur own OS:_ build SeedVault as a debug app (u likely do **not** want that)
- or use _root_ to start that activity.. (u likely do **not** want that)
- find a "better" protection level for SeedVault? (see next)

the current in-use protection level `system` is [deprecated since API level 23](https://developer.android.com/reference/android/R.attr#protectionLevel) and as far as I understood a replacement for this would be:

`android:protectionLevel="signature|privileged"`
(`system` was an alias for `privileged`)

This alone will likely  not solve the issue for `am`. Depends on if the deprecation is already active and so the `system` flag gets completely ignored/has no effect but well I am not an app developer at all ;) at least it would explain why I am not able to use ADB on Android 13 even though adb should be part of the `system` flag (imho).

EDIT: so after testing around I was not able to find a proper protectionlevel which allows adb to start the activity. IMHO that restore activity should be simply accessible from within Seedvault. I don't get why this is not there by default but maybe to avoid that users restore without thinking (and so overwriting a working system). anyways. the only workaround I found was: https://github.com/AXP-OS/android_packages_apps_Seedvault/commit/bc73d0fca637b45c0e05dd6b1dbdf9d71f88ca9b . after that the activity can be started as described in that commit msg.
