### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by DamienCassou** [stevesoltys/backup#507]
The previous release is more than a year old. Is it time to build a new one?

**Comment by markcellus** [comment]
Yeah, the latest versions don't work for me. Backup just keeps failing with no reason why. So I came here looking to see if there was a later version that I was missing out on.

**Comment by chirayudesai** [comment]
There hasn't been a tagged release for a while, per https://github.com/seedvault-app/seedvault/releases

However, we mostly work in branches, and maintain the changelog too https://github.com/seedvault-app/seedvault/blob/android13/CHANGELOG.md

Also, these releases were just for reference, since we don't post any APKs there, and instead rely on ROMs to include the version.

I'd be happy to go back and tag the missing releases, but it'd just be for rerence.

**Comment by stevleibelt** [comment]
@DamienCassou do you feel like @chirayudesai  was able to answer your question?

If so, please close this ticket.

**Comment by DamienCassou** [comment]
Thank you for your answer.
