### ISSUE TITLE
implement backup rotation / limits

### ISSUE THREAD

**Issue by steadfasterX** [stevesoltys/backup#559]
According to https://github.com/seedvault-app/seedvault/discussions/337 SeedVault does not have a backup rotation implemented neither by disk space nor a user-chosen one.

Implementation ideas (all of them would be ideal to have, while 2. seems to be a good point to start with):

1. **auto-rotate** (i.e. overwrite oldest backup) when running out of disk space
    - this will likely require to have a rough estimate of the backup size before
 2. let the user set a **specific backup count**
     - most "easy" one as it is up to the user to have an eye on the available disk space
3. let the user set a **specific max disk space amount**
    - this will likely require to have a rough estimate of the backup size before the backup starts to write

**Comment by major-mayer** [comment]
I would definitely support this issue.
It's quite surprising to me that such a feature doesn't exist yet. 
I mean, how do you store your backups, if they will just grow and grow forever?
I just checked on my Nextcloud instance and Seedvault is already at over 100GB after just a few weeks, and I don't have many large apps:
![image](https://github.com/seedvault-app/seedvault/assets/17907799/415c6766-32c3-4846-acaf-6f29efbaeac5)

For me, this makes the app basically unusable, because I don't have unlimited storage.

**Comment by major-mayer** [comment]
I would definitely support this issue.
It's quite surprising to me that such a feature doesn't exist yet. 
I mean, how do you store your backups, if they will just grow and grow forever?
I just checked on my Nextcloud instance and Seedvault is already at over 100GB after just a few weeks, and I don't have many large apps:
![image](https://github.com/seedvault-app/seedvault/assets/17907799/415c6766-32c3-4846-acaf-6f29efbaeac5)

For me, this makes the app basically unusable, because I don't have unlimited storage.

**Comment by grote** [comment]
Related to #566

**Comment by julianfoad** [comment]
Issue #649 "Auto-pruning old snapshots when running out of storage" is a specific proposal for option 1.

**Comment by grote** [comment]
For now we'll do 1. with #750 By default we keep 3 daily snapshots and 2 weekly ones (one from this and one from last week). For 2. we can open a new ticket.
