### ISSUE TITLE
Calendar and clock backup

### ISSUE THREAD

**Issue by dot166** [stevesoltys/backup#592]
It would be amazing if seedvault was able to back up calanders and alarms from Lineageos deskclock (com.android.deskclock) and star (org.lineageos.star)

**Comment by grote** [comment]
In Android, Seedvault is not responsible for extracting data from apps for backup. Apps are responsible for this and signal backup support to the OS. Then Seedvault can pick up this data.

**Comment by andrzej-gmt** [comment]
As I understand, calendar data is a system database accessible by calendar provider, which is a system component. There are 2 kinds of apps accessing calendar data. There are calendar apps, which can display and set calendar events and sync agents, which perform synchronization with external account. No application expose calendar data for backup. Actually sync agents preform this role. So instead of local backup you can use Google, Nextcloud, Etesync or other agents to preserve your calendar data.

The only exception is local calendar - a special type of calendar data, which does not have a sync agent. For example system calendar of Lineage OS can create local calendar data, which unfortunately isn't supported by SeedVault, which works as a system backup for Lineage OS.

As a workaround for calendar backup I use [DecSync](https://github.com/39aldo39/DecSyncCC), which works as a sync agent with local directory as a destination. Then I include this local directory to SeedVault backup.

**Comment by grote** [comment]
Related to #535

**Comment by grote** [comment]
I'll close this in favor of #535
