### ISSUE TITLE
In Dark Mode, grayed-out menu items look like normal menu items

### ISSUE THREAD

**Issue by t-m-w** [stevesoltys/backup#763]
Screenshots:
| Light | Dark |
| --- | --- |
| <img src="https://github.com/user-attachments/assets/d48390c2-c95e-420a-bdae-41b754534535" width="240" /> | <img src="https://github.com/user-attachments/assets/0655bf43-195f-48ea-b492-79cb4a3d74b5" width="240" /> |

The Light screenshot shows grayed-out "Backup now" and "Restore backup" menu items. The Dark screenshot shows "Backup now" and "Restore backup" menu items that are the same color as the others.

The effect is that the user may be confused by nothing happening when they tap one of these items.

May be related to https://github.com/seedvault-app/seedvault/pull/750

**Comment by grote** [comment]
@theimpulson I think this is related to your MD3 changes. Do you know how to bring back disabled menu items in dark theme?

**Comment by theimpulson** [comment]
This should be fixed by dropping the theme attribute from the `Toolbar`. I have included this in https://github.com/seedvault-app/seedvault/pull/776 PR but we can move it to a standalone one too if required.

https://github.com/seedvault-app/seedvault/pull/776/commits/dc0a511fbc901567a752d46c6faa967ea4bf3cd3
